parameters:
    nt.locations.admin.locations.class: NT\LocationsBundle\Admin\LocationsAdmin
    nt.locations.admin.locations.controller: NTCoreBundle:SortableCRUD
    nt.locations.admin.locations.translation: NTLocationsBundle


services:
    nt.locations.admin.locations:
        class: %nt.locations.admin.locations.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: "nt_site", label: "nt_locations" }
        arguments:
            - ~
            - %nt.locations.admin.locations.entity%
            - %nt.locations.admin.locations.controller%
        calls:
            - [ setTranslationDomain, [%nt.locations.admin.locations.translation%]]
            - [ setTemplates, [outer_list_rows_mosaic: NTCoreBundle:Admin:list_outer_rows_mosaic.html.twig]]