parameters:
    nt.companies.admin.companies.translation: NTCompaniesBundle

services:
    nt.publish_company.form.type:
        class: NT\CompaniesBundle\Form\Type\PublishCompanyType
        tags:
            - { name: form.type, alias: publish_company }

    nt.companies.admin.companies:
        class: NT\CompaniesBundle\Admin\CompaniesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "nt_site_companies", label: "nt_companies", audit: true }
        arguments:
            - ~
            - NT\CompaniesBundle\Entity\Company
            - NTCompaniesBundle:CompaniesBackend
        calls:
            - [ setTranslationDomain, [%nt.companies.admin.companies.translation%]]
            - [ setTemplates, [outer_list_rows_mosaic: NTCoreBundle:Admin:list_outer_rows_mosaic.html.twig]]

    nt.company_categories.admin.company_category:
        class: NT\CompaniesBundle\Admin\CompanyCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "nt_site_companies", label: "nt_company_categories", audit: true }
        arguments:
            - ~
            - NT\CompaniesBundle\Entity\CompanyCategory
            - NTCoreBundle:TreeCRUD
        calls:
            - [ setTranslationDomain, [%nt.companies.admin.companies.translation%]]
            - [ setTemplates, [outer_list_rows_mosaic: NTCoreBundle:Admin:list_outer_rows_mosaic.html.twig]]

    nt.companies.admin.companies_translations:
        class: NT\CompaniesBundle\Admin\CompaniesTranslationsAdmin
        arguments: [~, NT\CompaniesBundle\Entity\CompanyTranslation, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        calls:
            - [ setTranslationDomain, [%nt.companies.admin.companies.translation%]]

    nt.companies.admin.company_category_translations:
        class: NT\CompaniesBundle\Admin\CompanyCategoryTranslationsAdmin
        arguments: [~, NT\CompaniesBundle\Entity\CompanyCategoryTranslation, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, show_in_dashboard: false}
        calls:
            - [ setTranslationDomain, [%nt.companies.admin.companies.translation%]]

    nt.companies.admin.companies_addresses:
        class: NT\CompaniesBundle\Admin\CompaniesAddressesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "nt_site_companies_addresses", label: "nt_companies_addresses" }
        arguments:
            - ~
            - NT\CompaniesBundle\Entity\CompanyAddress
            - NTCoreBundle:SortableCRUD
        calls:
            - [ setTranslationDomain, [%nt.companies.admin.companies.translation%]]
            - [ setTemplates, [outer_list_rows_mosaic: NTCoreBundle:Admin:list_outer_rows_mosaic.html.twig]]
